// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/braiphub/go-core/cache (interfaces: Cacherer)
//
// Generated by this command:
//
//	mockgen -destination=cache_mock.go -package=cache . Cacherer
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacherer is a mock of Cacherer interface.
type MockCacherer struct {
	ctrl     *gomock.Controller
	recorder *MockCachererMockRecorder
	isgomock struct{}
}

// MockCachererMockRecorder is the mock recorder for MockCacherer.
type MockCachererMockRecorder struct {
	mock *MockCacherer
}

// NewMockCacherer creates a new mock instance.
func NewMockCacherer(ctrl *gomock.Controller) *MockCacherer {
	mock := &MockCacherer{ctrl: ctrl}
	mock.recorder = &MockCachererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacherer) EXPECT() *MockCachererMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCacherer) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCachererMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacherer)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockCacherer) Get(ctx context.Context, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCachererMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacherer)(nil).Get), ctx, key)
}

// GetInt mocks base method.
func (m *MockCacherer) GetInt(ctx context.Context, key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt", ctx, key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInt indicates an expected call of GetInt.
func (mr *MockCachererMockRecorder) GetInt(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt", reflect.TypeOf((*MockCacherer)(nil).GetInt), ctx, key)
}

// GetString mocks base method.
func (m *MockCacherer) GetString(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetString indicates an expected call of GetString.
func (mr *MockCachererMockRecorder) GetString(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockCacherer)(nil).GetString), ctx, key)
}

// GetUint mocks base method.
func (m *MockCacherer) GetUint(ctx context.Context, key string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUint", ctx, key)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUint indicates an expected call of GetUint.
func (mr *MockCachererMockRecorder) GetUint(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUint", reflect.TypeOf((*MockCacherer)(nil).GetUint), ctx, key)
}

// Set mocks base method.
func (m *MockCacherer) Set(ctx context.Context, key string, value any, duration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, duration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCachererMockRecorder) Set(ctx, key, value, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacherer)(nil).Set), ctx, key, value, duration)
}

// TestConnection mocks base method.
func (m *MockCacherer) TestConnection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockCachererMockRecorder) TestConnection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockCacherer)(nil).TestConnection), ctx)
}
