version: '3.9'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  grafana:
    image: grafana/grafana:10.2.2
    volumes:
      - ./configs/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3000:3000"
    depends_on:
      - tempo
    logging: *default-logging

  tempo:
    image: grafana/tempo:2.3.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
    #      - ./tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo http
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    logging: *default-logging

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./configs/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    logging: *default-logging

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    logging: *default-logging



#  k6-tracing:
#     image: ghcr.io/grafana/xk6-client-tracing:latest
#     environment:
#       - ENDPOINT=tempo:4317
#     restart: always
#     depends_on:
#       - tempo

  order-service:
    container_name: order-service
    build:
      context: order_service
    ports:
      - 5001:5000
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    logging: *default-logging

  payment-service:
    container_name: payment-service
    build:
      context: payment_service
    ports:
      - 5002:5000
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    logging: *default-logging