// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/braiphub/go-core/queue (interfaces: QueueI)
//
// Generated by this command:
//
//	mockgen -destination=interface_mock.go -package=queue . QueueI
//

// Package queue is a generated GoMock package.
package queue

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueueI is a mock of QueueI interface.
type MockQueueI struct {
	ctrl     *gomock.Controller
	recorder *MockQueueIMockRecorder
	isgomock struct{}
}

// MockQueueIMockRecorder is the mock recorder for MockQueueI.
type MockQueueIMockRecorder struct {
	mock *MockQueueI
}

// NewMockQueueI creates a new mock instance.
func NewMockQueueI(ctrl *gomock.Controller) *MockQueueI {
	mock := &MockQueueI{ctrl: ctrl}
	mock.recorder = &MockQueueIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueI) EXPECT() *MockQueueIMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockQueueI) Consume(ctx context.Context, queue string, fn func(context.Context, Message) error, opts ...func(*ConsumeOptions)) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, queue, fn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Consume", varargs...)
}

// Consume indicates an expected call of Consume.
func (mr *MockQueueIMockRecorder) Consume(ctx, queue, fn any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, queue, fn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockQueueI)(nil).Consume), varargs...)
}

// ConsumeStream mocks base method.
func (m *MockQueueI) ConsumeStream(ctx context.Context, eventName string, fn func(context.Context, Message) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConsumeStream", ctx, eventName, fn)
}

// ConsumeStream indicates an expected call of ConsumeStream.
func (mr *MockQueueIMockRecorder) ConsumeStream(ctx, eventName, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeStream", reflect.TypeOf((*MockQueueI)(nil).ConsumeStream), ctx, eventName, fn)
}

// Produce mocks base method.
func (m *MockQueueI) Produce(ctx context.Context, eventName string, msg any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, eventName, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockQueueIMockRecorder) Produce(ctx, eventName, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockQueueI)(nil).Produce), ctx, eventName, msg)
}
